config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :tickets
  root to: "welcome#show"
#Obsluga kupna ticketu na event
  scope 'charge' do
        post 'create', to: 'charge#create', as: 'charge_create'
        get 'cancel', to: 'charge#cancel', as: 'charge_cancel'
        get 'success', to: 'charge#success', as: 'charge_success'
        end
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates_presence_of :Title, :Date, :Time, :Tickets, :Price
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :wallet
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    validates_presence_of :Event_id, :amount
    belongs_to :wallet
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_one :wallet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
def reset_session
  @_request.reset_session
end

end

app/controllers/charge_controller.rb
class ChargeController < ApplicationController
  before_action :require_login

  def create
          @event = Event.find(params[:id])
	  if @event.nil?
             redirect_to root_path
             return
          end
           session[:current_id] = @event.id
	   session[:current_tickets] = @event.Tickets
	  #setting up Stripe session for payment
	    #setting up Stripe session for payment
	  @session = Stripe::Checkout::Session.create(
                        payment_method_types: ['card'],
                        line_items: [{
                          name: @event.Title,
                          description: 'Bought ticket for event',
			  amount: @event.Price,
                          currency: 'eur',
                          quantity: 1
                        }],
                        success_url: charge_success_url,
                        cancel_url: charge_cancel_url
                )
          respond_to do |format|
            format.js #render create.js.erb
	  end
        end
	
	def success
		@event = Event.find(session[:current_id])
		@update = @event.update(Tickets: session[:current_tickets]-1)
		@result = Ticket.new(Event_id: session[:current_id], amount: 1 )
		@result.save
	end

	def cancel
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login
  before_action :set_event, only: %w[ show edit update destroy ]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:Title, :Date, :Time, :Tickets, :Price)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :require_login
  before_action :set_stock, only: %w[ show edit update destroy ]
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all

  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:name, :ammount, :close_price, :open_price, :high, :low)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :require_login
  before_action :set_ticket, only: %w[ show edit update destroy ]
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:Event_id, :amount)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_login

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charge_helper.rb
module ChargeHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/charge/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
 sessionId: '<%= @session.id %>'
}).then(function(result){
  console.log(result.error.message);
});

app/views/charge/success.html.erb
<h1> Success, We took your Money! </h1>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Date %>
    <%= form.date_select :Date %>
  </div>

  <div class="field">
    <%= form.label :Time %>
    <%= form.datetime_select :Time %>
  </div>

  <div class="field">
    <%= form.label :Tickets %>
    <%= form.number_field :Tickets , {min: 1, max: 50}%>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.number_field :Price , {min: 50, max: 1000}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= javascript_pack_tag 'hello_react' %>
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Time</th>
      <th>Tickets</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.Title %></td>
        <td><%= event.Date %></td>
        <td><%= event.Time %></td>
        <td><%= event.Tickets %></td>
        <td><%= event.Price %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
 <head>
   <script src="https://js.stripe.com/v3/"></script>
 </head>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.Title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.Date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.Time %>
</p>

<p>
  <strong>Tickets:</strong>
  <%= @event.Tickets %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.Price %>
</p>
<%= number_field_tag 'amount', nil, :min => 1, :max => @event.Tickets - 1 %>


<%= button_to 'Buy', charge_create_path, method: :post, params: { id: @event.id, quantity: params[:amount]  }, remote:true %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketingCheckout</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ammount %>
    <%= form.number_field :ammount %>
  </div>

  <div class="field">
    <%= form.label :close_price %>
    <%= form.text_field :close_price %>
  </div>

  <div class="field">
    <%= form.label :open_price %>
    <%= form.text_field :open_price %>
  </div>

  <div class="field">
    <%= form.label :high %>
    <%= form.text_field :high %>
  </div>

  <div class="field">
    <%= form.label :low %>
    <%= form.text_field :low %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ammount</th>
      <th>Close price</th>
      <th>Open price</th>
      <th>High</th>
      <th>Low</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.ammount %></td>
        <td><%= stock.close_price %></td>
        <td><%= stock.open_price %></td>
        <td><%= stock.high %></td>
        <td><%= stock.low %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Ammount:</strong>
  <%= @stock.ammount %>
</p>

<p>
  <strong>Close price:</strong>
  <%= @stock.close_price %>
</p>

<p>
  <strong>Open price:</strong>
  <%= @stock.open_price %>
</p>

<p>
  <strong>High:</strong>
  <%= @stock.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @stock.low %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Event_id %>
    <%= form.number_field :Event_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.Event_id %></td>
        <td><%= ticket.amount %></td>
        <td><%= link_to 'Show', ticket %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @ticket.Event_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @ticket.amount %>
</p>

<%= link_to 'Back', tickets_path %>

app/views/welcome/show.html.erb
<h1> Welcome </h1>
<%= link_to 'Events', events_path %>
<%= link_to 'Tickets', tickets_path %>
<%= link_to 'Stocks', stocks_path %>